@startuml
'https://plantuml.com/class-diagram

top to bottom direction
'skinparam linetype ortho
title Domain Model Diagram

class Person {
    name : Text
    phone_number : Integer
    email : Text
}
class NurseUser {
    nurse_id : Integer
}
class SNSUser {
    sns_number : Integer
    birth_date : Date
    sex : Text
    cc_number : Text
}
class ReceptionistUser {
    receptionist_id : Integer
}
class DGSAdminUser {
    admin_id : Integer
}
class Vaccine {
    name : Text
    brand : Text
    tech_used : Text
    lot : Text
}
class Appointment {
    state : Integer
    reaction : Text
}
enum StatusAppointment {
    TO_BE_ATTENDED : Integer
    ATTENDING : Integer
    VACCINATED : Integer
    LEAVING : Integer
}
class Institution {
    name : Text
    phone_number : Integer
    website : Text
    max_vaccines_per_hour : Integer
}
class HealthCareCenter {
}
class CommunityCenter {
}
class Address {
    street : Text
    door_number : Text
    zip_code : Text
    city : Text
}

class AppointmentDate {
    year : Integer
    month : Integer
    day  : Integer
    hour : Integer
    minute : Integer
}
class Hours {
    hour : Integer
    minute : Integer
}
class HealthRecord {
}
class OpeningHours {
}
class Disease {
    name : Text
    start : Date
}

Person <|-- NurseUser
Person <|---- SNSUser
Person <|-- ReceptionistUser
Person <|-- DGSAdminUser
Person "1..*    " - "1    "  Address: resides in >
Institution <|-- HealthCareCenter
Institution <|-- CommunityCenter
HealthCareCenter "1" --- "*" Vaccine: administers >
CommunityCenter "1" --- "\n \n \n \n \n \n \n \n \n \n *      " Vaccine: administers >
SNSUser "1    " --- "1  " HealthRecord: possesses >
HealthRecord "1   " -- "*" Appointment: < has registered
Institution "1        " --- "1 " Address: exists in >
Institution "1" -- "1..*                 " OpeningHours: operate in >
DGSAdminUser "1" -- "1   " Disease: "\n indicates >"
Appointment "                            *" --- "1    " SNSUser: < schedules
Appointment "*" -- "1" Institution: < effectuates
Appointment "1   " -- "1" AppointmentDate: is schedule on >
Appointment "1" -- "1  " Vaccine: < is administrated during
Appointment "1..*   " -- "1 " StatusAppointment: is on a >
Disease "1" -- "*" Vaccine: < treats
Hours "2 " -- "1 " OpeningHours: "\n \n \ndescribes >"

@enduml