@startuml
'https://plantuml.com/class-diagram

top to bottom direction
'skinparam linetype ortho
title Domain Model Diagram

enum EmployeeType {
    NURSE : Integer
    RECEPTIONIST : Integer
}
class Employee {
    employee_id : Integer
    name : Text
    phone_number : Integer
    email : Text
    zip_code : Text
}
class SNSUser {
    name : Text
    birth_date : Date
    sex : Text
    zip_code : Text
    phone_number : Integer
    email : Text
    cc_number : Integer
    sns_number : Integer
}
class DGSAdminUser {}
class Vaccine {
    name : Text
    brand : Text
    tech_used : Text
    lot : Text
}
class Appointment {
    state : Integer
    reaction : Text
}
enum StatusAppointment {
    TO_BE_ATTENDED : Integer
    ATTENDING : Integer
    VACCINATED : Integer
    LEAVING : Integer
}
enum InstitutionType {
    HEALTHCARE_CENTER : Integer
    COMMUNITY_CENTER : Integer
}
class Institution {
    name : Text
    zip_code : Text
    phone_number : Integer
    email : Text
    website : Text
    max_vaccines_per_hour : Integer
}
class AppointmentDate {
    year : Integer
    month : Integer
    day  : Integer
    hour : Integer
    minute : Integer
}
class Hours {
    hour : Integer
    minute : Integer
}
class HealthRecord {
}
class OpeningHours {
}
class Disease {
    name : Text
    start : Date
}
Employee "*" - "1" EmployeeType: has a type of >
Employee "1" -- "*" Appointment: updates the status >
Institution "*" -- "1" InstitutionType: has a type of >
Institution "1" --- "* " Vaccine: administers >
SNSUser "1  " --- "1" HealthRecord: possesses >
HealthRecord "1   " -- "*" Appointment: has registered >
Institution "1" -- "2" OpeningHours: operate in >
DGSAdminUser "1" -- "1   " Disease: "\n indicates >"
Appointment "*" -- "1    " SNSUser: < schedules
Appointment "*" -- "1" Institution: < effectuates
Appointment "1   " -- "1" AppointmentDate: is schedule on >
Appointment "1" -- "1  " Vaccine: < is administrated during
Appointment "1..*   " -- "1 " StatusAppointment: is on a >
Disease "1" -- "*" Vaccine: < treats
Hours "2" -- "1" OpeningHours: "describes >"

@enduml