@startuml
title US11 - Sequence Diagram: Register a Vaccine
autonumber

actor "DGS Administrator" as Admin
participant ":VaccineRegistrationView" as View
participant ":VaccineController" as Controller
participant ":VaccineContainer" as Container
participant "Vaccine" as Vaccine


Admin -> View: Request to register new vaccine
View --> Admin: Display registration form

Admin -> View: Enter vaccine details
View -> Controller: registerVaccine

Controller -> Container: registerNewVaccine


Container -> Container: validatevaccinefields

alt Vaccine is valid
    Container -> Vaccine: CreateVaccine
    Container -> Container: AddVaccineToRepository
    Container --> Controller: Success message
else Vaccine is invalid
    Container --> Controller: Error message ("Invalid vaccine")
end

Controller --> View: Return result

View -> Admin: Show confirmation or error message

@enduml