@startuml
'https://plantuml.com/sequence-diagram

title   US11 - Sequence Diagram
autonumber

actor "DGS Administrator" as Admin
participant ":System" as System
participant ":Vaccine" as Vaccine

Admin -> System: Requests to register a new vaccine
System --> Admin: Displays the vaccine registration form

Admin -> System: Submits new vaccine details


alt Valid Data
    System -> Vaccine: Create Vaccine
    Vaccine --> System: Returns new Vaccine object

    System --> Admin: Displays confirmation message: "Vaccine registered successfully!"
end

@enduml