@startuml
'https://plantuml.com/sequence-diagram

title US15 System Sequence Diagram

autoactivate on
autonumber

actor "Admin" as Admin
participant ":System" as System

activate Admin

Admin -> System: Requests for the employees list
System --> Admin: Requests the employee's assigned role/function

Admin -> System: Inputs the employee's assigned role/function
System --> Admin: Returns the requested list

@enduml