@startuml
' US15 Domain Model Excerpt
title US15 - Domain Model

skinparam classAttributeIconSize 0
enum EmployeeType {
    + NURSE : Integer
    + RECEPTIONIST : Integer
}

class Person {
  name : Text
  phone_number : Integer
  email : Text
}

class Employee extends Person {
    employee_id : Integer
}
@enduml