@startuml
' US15 Domain Model Excerpt
title US15 - Domain Model

skinparam classAttributeIconSize 0

class Person {
  name : Text
  phone_number : Integer
  email : Text
}

class NurseUser extends Person {
  nurse_id : Integer
}

class ReceptionistUser extends Person{
  receptionist_id : Integer
}

class DGSAdminUser extends Person{
  admin_id : Integer
}

@enduml