@startuml
title US15 - Sequence Diagram

actor "Admin" as Admin
participant ":GetEmployeeListView" as View
participant ":GetEmployeeListController" as Controller
participant ":NurseContainer" as NurseRepo
participant ":ReceptionistContainer" as RecRepo

autonumber

activate Admin
Admin -> View: Asks to get employee list by role/function
View --> Admin: Shows List of Available roles (Nurse, Receptionist)
Admin -> View: Selects the requested role
View -> Controller: getEmployeeList(role)

alt role is "Nurse"
    Controller -> NurseRepo: getNurseList()
    NurseRepo --> Controller: list<NurseUser>
else role is "Receptionist"
    Controller -> RecRepo: getReceptionistList()
    RecRepo --> Controller: list<ReceptionistUser>
end

Controller --> View: Returns the list
View --> Admin: Returns the requested list

@enduml