@startuml
'https://plantuml.com/sequence-diagram
title US15 - Get Employee List by Role (SSD)

autoactivate on
autonumber

actor "Admin" as Admin
participant ":System" as System

activate Admin

Admin -> System: Asks to get employee list by role/function
System --> Admin: Shows list of available roles (e.g., Nurse, Receptionist)

Admin -> System: Selects the employee's assigned role/function
System --> Admin: Returns the requested list

@enduml