@startuml
title US15 - Sequence Diagram

autoactivate on
autonumber

actor "Admin" as Admin
participant ":GetEmployeeListView" as View
participant ":GetEmployeeListController" as Controller
participant ":EmployeeContainer" as EmploRepo

activate Admin
Admin -> View: Asks to get employee list by role/function
View --> Admin: Shows List of Available roles (Nurse, Receptionist)
Admin -> View: Selects the requested role
View -> Controller: getEmployeeList(role)

alt role is 0
    Controller -> EmploRepo: getNurseList()
    EmploRepo --> Controller: list<Employee>
else role is 1
    Controller -> EmploRepo: getReceptionistList()
    EmploRepo --> Controller: list<Employee>
end

Controller --> View: Returns the list
View --> Admin: Returns the requested list

@enduml