@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods

title US14's Domain Model

enum EmployeeType {
    NURSE : Integer
    RECEPTIONIST : Integer
}
class Employee {
    employee_id : Integer
    name : Text
    phone_number : Integer
    email : Text
    zip_code : Text
}

Employee "*" -- "1" EmployeeType: has a type of >


@enduml