@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

title US14's Sequence Diagram

actor "Administrator" as Admin
participant ":RegisterEmployeeView" as REV
participant ":RegisterEmployeeController" as REC
participant "employee : Employee" as EMP
participant ":EmployeeContainer" as EC

activate Admin

Admin -> REV: Request an employee registration

REV --> Admin: Clarifies the type of employee
Admin -> REV: Inputs the type of employee
REV --> Admin: Shows the required input fields
Admin -> REV: Inputs the necessary typed information
REV -> REC: registerEmployee(type, name, phone_number, email, zip_code)
REC -> EMP: setType(type)
EMP --> REC: ok
REC -> EMP: setID(employee_id++)
EMP --> REC: ok
REC -> EMP: setName(name)
EMP --> REC: ok
REC -> EMP: setPhoneNumber(phone_number)
EMP --> REC: ok
REC -> EMP: setEmail(email)
EMP --> REC: ok
REC -> EMP: setZipCode(zip_code)
EMP --> REC: ok
REC -> EC: add(employee)
EC --> REC: success
REC --> REV: success
REV --> Admin: success





@enduml